# Generated by Django 3.1.3 on 2020-11-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_signalling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user_id',
        ),
    ]
