# Generated by Django 3.1.3 on 2020-11-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_signalling', '0002_remove_clients_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
